### ISSUE TITLE
Send auth credentials

### ISSUE THREAD

**Issue by rasmuslos** [ItalyPaleAle/prvt#30]
If you want to access prvt over the Internet, it makes sense to put an authentication such as the Basic HTTP auth in between. Currently, this does not work because this [line](https://github.com/ItalyPaleAle/prvt/blob/befe766b534e11c1a09f7c9ff20377375525e4bb/ui/src/shared/request.ts#L36) prevents credentials from being sent, which makes all fetch requests impossible

[mdn](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#requests_with_credentials) & also [mdn](https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials)

**Comment by ItalyPaleAle** [comment]
Closing to continue the conversation on #31
