### ISSUE TITLE
Private vulnerabiity reporting feature

### ISSUE THREAD

**Issue by Sim4n6** [ItalyPaleAle/prvt#84]
Hi, I have identified a vulnerability in the latest codebase of prvt. I would like to privately report it via [GitHub Private reporting feature](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository). Could you please consider enabling that ?

**Comment by ItalyPaleAle** [comment]
Done, thanks! Will look for it

**Comment by Sim4n6** [comment]
Done !

**Comment by ItalyPaleAle** [comment]
Thank you @Sim4n6, I saw the report! I am on vacation for a few more days. I agree this is a vulnerability, but since doesn’t seem extremely urgent, I will address it upon my return.
